Web/SPDD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from userprofile.views import signup
from django.urls import path, include
from django.shortcuts import redirect
from userprofile.forms import LoginForm

urlpatterns = [
    path('', lambda request: redirect('login')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('sign-up/', signup, name='signup'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/client/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('export/', views.clients_export, name='export'),
    path('add/', views.clients_add, name='add'),
]

Web/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='index'),
    path('make_payment/', views.make_payment, name='make_payment'),
    path('payment_success/', views.payment_success, name='payment_success'),
]

Web/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

Web/team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),
    path('select-team-plan/', views.select_team_plan, name='select_team_plan'),
    path('payment/', views.payment, name='payment'),
    path('create-payment-intent/', views.create_payment_intent, name='create_payment_intent'),
]

Web/core/views.py
from django.shortcuts import render

Web/core/templates/core/partials/footer.html
<footer class="py-8 text-center bg-gray-200">
    <p class="text-xs text-gray-700">Copyright (c) 2024 - CRM</p>
</footer>

Web/core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-teal-500">
    <p class="text-white">CRM SPDD</p>

    <div class="space-x-4">
        {% if request.user.is_authenticated %}
            <a href="{% url 'team:detail' active_team.id %}" class="text-white">{{ active_team.name }}</a>
            <a href="{% url 'dashboard:index' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Dashboard</a>
            <a href="{% url 'leads:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Leads</a>
            <a href="{% url 'clients:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Clients</a>
            <a href="{% url 'userprofile:myaccount' %}" class="py-4 px-6 bg-teal-800 rounded-xl text-white">My account</a>
        {% else %}
            <a href="{% url 'login' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Log in</a>
            <a href="{% url 'signup' %}" class="py-4 px-6 bg-teal-300 rounded-xl text-white">Sign up</a>
        {% endif %}
    </div>
</nav>